version: 2.1

# --- Anchor alias ---- #
# - Docker configuration - #
alias:
  - &node_executor
    executor:
      name: node/default
      # See https://circleci.com/developer/orbs/orb/circleci/node for available tags.
      tag: "14.15"
  - &docker_buildpack_deps_configuration
    docker:
      - image: circleci/buildpack-deps:stretch
        user: root
# - Jobs filters - #
  - &filters_ignore_tags
    tags:
      ignore: /.*/
  - &filters_branch_allow_all
    tags:
      only: /.*/
  - &filters_branch_tags_all
    tags:
      only: /.*/
# - Node modules - #
  - &install_npm
    node/install-npm:
      version: "7"
  - &install_dependencies
    node/install-packages:
      cache-version: "{{ .Environment.CACHE_VERSION }}"
      include-branch-in-cache-key: false
      override-ci-command: npm ci --no-audit
# --- Anchor alias ---- #
jobs:
  build:
    <<: *node_executor
    steps:
      - checkout
      - *install_npm
      - *install_dependencies
      - run: export NODE_ENV=production; npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build
  lint:
    <<: *node_executor
    steps:
      - checkout
      - *install_npm
      - *install_dependencies
      - run: npm run lint
  docker-build:
    <<: *docker_buildpack_deps_configuration
    steps:
      - checkout
      - setup_remote_docker  
      - attach_workspace:
          at: ~/project
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
orbs:
  node: circleci/node@4.1.0
  docker: circleci/docker@0.5.20
# --- END --- #
workflows:
  build:
    jobs:
      - build:
          filters:
            <<: *filters_branch_allow_all
            <<: *filters_branch_tags_all
      - lint:
          filters:
            <<: *filters_branch_allow_all
            <<: *filters_branch_tags_all
      - docker-build:
          requires:
            - lint
            - build
          filters:
            <<: *filters_branch_allow_all
            <<: *filters_branch_tags_all
